name: "SNS publish"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: "SNS"
    runs-on: ubuntu-latest
    steps:
      - name: AWS SNS
        uses: nothingalike/sns-publish-topic@v1.5
        if: github.event_name == 'pull_request'
        with:
          MESSAGE: "PR for prod raised, please approve"
          TOPIC_ARN: "arn:aws:sns:eu-west-2:915501751518:prod-release:38db38a2-c61d-4d3c-9bc4-36bc728be997"
        env:
          AWS_REGION: "eu-west-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: false